name: Build Feature Branch

on:
  push:
    branches: 'feature/**'

jobs:
    coverage:
      runs-on: ps-acquirer
      steps:
        - uses: ps-acquirer/checkout@v2

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          env:
            ANDROID_HOME: "/home/grunner/tools/android"
          run: ./gradlew jacocoCoverageReport

        - name: Generate Jacoco Badge
          id: jacoco
          uses: cicirello/jacoco-badge-generator@v1.0.0

        - name: Log coverage percentage
          run: |
            echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

        - name: Upload Jacoco coverage report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: target/site/jacoco/

        - name: Upload Coverage Reports
          if: ${{ always() }}
          uses: ps-acquirer/upload-artifact@v2
          with:
            name: Coverage-report
            path: '**/build/reports/jacoco/'
